/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RiskAssessmentInput = IDL.Record({
  'prInterval' : IDL.Nat,
  'ultrasoundImage' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'stSegment' : IDL.Float64,
  'qrsDuration' : IDL.Nat,
  'temperature' : IDL.Float64,
  'spo2' : IDL.Nat,
  'complexes' : IDL.Text,
  'qtInterval' : IDL.Nat,
  'rrInterval' : IDL.Nat,
  'heartRate' : IDL.Nat,
});
export const Finding = IDL.Record({
  'status' : IDL.Text,
  'value' : IDL.Text,
  'parameter' : IDL.Text,
  'referenceRange' : IDL.Text,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'moderate' : IDL.Null,
});
export const RiskReport = IDL.Record({
  'findings' : IDL.Vec(Finding),
  'disclaimer' : IDL.Text,
  'clinicalExplanation' : IDL.Text,
  'riskLevel' : RiskLevel,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const SessionToken = IDL.Text;
export const UserId = IDL.Principal;
export const Email = IDL.Text;
export const User = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'salt' : IDL.Vec(IDL.Nat8),
  'email' : Email,
  'passwordHash' : IDL.Vec(IDL.Nat8),
});
export const ReportId = IDL.Nat;
export const SavedReport = IDL.Record({
  'id' : ReportId,
  'report' : RiskReport,
  'createdAt' : IDL.Int,
});
export const AuthError = IDL.Variant({
  'invalidEmail' : IDL.Null,
  'emailTaken' : IDL.Null,
  'notAuthenticated' : IDL.Null,
  'weakPassword' : IDL.Null,
  'invalidCredentials' : IDL.Null,
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Vec(SavedReport),
  'err' : AuthError,
});
export const Result_2 = IDL.Variant({ 'ok' : SessionToken, 'err' : AuthError });
export const Result_1 = IDL.Variant({ 'ok' : SavedReport, 'err' : AuthError });
export const Result = IDL.Variant({ 'ok' : User, 'err' : AuthError });

export const idlService = IDL.Service({
  'assessRisk' : IDL.Func([RiskAssessmentInput], [RiskReport], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCurrentUser' : IDL.Func([SessionToken], [IDL.Opt(User)], ['query']),
  'getMyReports' : IDL.Func([SessionToken], [Result_3], ['query']),
  'login' : IDL.Func([Email, IDL.Text], [Result_2], []),
  'logout' : IDL.Func([SessionToken], [], []),
  'saveReport' : IDL.Func([SessionToken, RiskReport], [Result_1], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'signup' : IDL.Func([IDL.Text, Email, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RiskAssessmentInput = IDL.Record({
    'prInterval' : IDL.Nat,
    'ultrasoundImage' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'stSegment' : IDL.Float64,
    'qrsDuration' : IDL.Nat,
    'temperature' : IDL.Float64,
    'spo2' : IDL.Nat,
    'complexes' : IDL.Text,
    'qtInterval' : IDL.Nat,
    'rrInterval' : IDL.Nat,
    'heartRate' : IDL.Nat,
  });
  const Finding = IDL.Record({
    'status' : IDL.Text,
    'value' : IDL.Text,
    'parameter' : IDL.Text,
    'referenceRange' : IDL.Text,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const RiskReport = IDL.Record({
    'findings' : IDL.Vec(Finding),
    'disclaimer' : IDL.Text,
    'clinicalExplanation' : IDL.Text,
    'riskLevel' : RiskLevel,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const SessionToken = IDL.Text;
  const UserId = IDL.Principal;
  const Email = IDL.Text;
  const User = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'salt' : IDL.Vec(IDL.Nat8),
    'email' : Email,
    'passwordHash' : IDL.Vec(IDL.Nat8),
  });
  const ReportId = IDL.Nat;
  const SavedReport = IDL.Record({
    'id' : ReportId,
    'report' : RiskReport,
    'createdAt' : IDL.Int,
  });
  const AuthError = IDL.Variant({
    'invalidEmail' : IDL.Null,
    'emailTaken' : IDL.Null,
    'notAuthenticated' : IDL.Null,
    'weakPassword' : IDL.Null,
    'invalidCredentials' : IDL.Null,
  });
  const Result_3 = IDL.Variant({
    'ok' : IDL.Vec(SavedReport),
    'err' : AuthError,
  });
  const Result_2 = IDL.Variant({ 'ok' : SessionToken, 'err' : AuthError });
  const Result_1 = IDL.Variant({ 'ok' : SavedReport, 'err' : AuthError });
  const Result = IDL.Variant({ 'ok' : User, 'err' : AuthError });
  
  return IDL.Service({
    'assessRisk' : IDL.Func([RiskAssessmentInput], [RiskReport], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCurrentUser' : IDL.Func([SessionToken], [IDL.Opt(User)], ['query']),
    'getMyReports' : IDL.Func([SessionToken], [Result_3], ['query']),
    'login' : IDL.Func([Email, IDL.Text], [Result_2], []),
    'logout' : IDL.Func([SessionToken], [], []),
    'saveReport' : IDL.Func([SessionToken, RiskReport], [Result_1], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'signup' : IDL.Func([IDL.Text, Email, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };