/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthError = { 'invalidEmail' : null } |
  { 'emailTaken' : null } |
  { 'notAuthenticated' : null } |
  { 'weakPassword' : null } |
  { 'invalidCredentials' : null };
export interface Cell { 'value' : Value, 'name' : string }
export type Email = string;
export interface Finding {
  'status' : string,
  'value' : string,
  'parameter' : string,
  'referenceRange' : string,
}
export type ReportId = bigint;
export type Result = { 'ok' : User } |
  { 'err' : AuthError };
export type Result_1 = { 'ok' : SavedReport } |
  { 'err' : AuthError };
export type Result_2 = { 'ok' : SessionToken } |
  { 'err' : AuthError };
export type Result_3 = { 'ok' : Array<SavedReport> } |
  { 'err' : AuthError };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface RiskAssessmentInput {
  'prInterval' : bigint,
  'ultrasoundImage' : [] | [Uint8Array],
  'stSegment' : number,
  'qrsDuration' : bigint,
  'temperature' : number,
  'spo2' : bigint,
  'complexes' : string,
  'qtInterval' : bigint,
  'rrInterval' : bigint,
  'heartRate' : bigint,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'moderate' : null };
export interface RiskReport {
  'findings' : Array<Finding>,
  'disclaimer' : string,
  'clinicalExplanation' : string,
  'riskLevel' : RiskLevel,
}
export interface SavedReport {
  'id' : ReportId,
  'report' : RiskReport,
  'createdAt' : bigint,
}
export type SessionToken = string;
export interface User {
  'id' : UserId,
  'name' : string,
  'createdAt' : bigint,
  'salt' : Uint8Array,
  'email' : Email,
  'passwordHash' : Uint8Array,
}
export type UserId = Principal;
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  'assessRisk' : ActorMethod<[RiskAssessmentInput], RiskReport>,
  'execute' : ActorMethod<[string], Result__1>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCurrentUser' : ActorMethod<[SessionToken], [] | [User]>,
  'getMyReports' : ActorMethod<[SessionToken], Result_3>,
  'login' : ActorMethod<[Email, string], Result_2>,
  'logout' : ActorMethod<[SessionToken], undefined>,
  'saveReport' : ActorMethod<[SessionToken, RiskReport], Result_1>,
  'schema' : ActorMethod<[], string>,
  'signup' : ActorMethod<[string, Email, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];