/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Result_2 = {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: AuthError;
};
export interface User {
    id: UserId;
    name: string;
    createdAt: bigint;
    salt: Uint8Array;
    email: Email;
    passwordHash: Uint8Array;
}
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result_1 = {
    __kind__: "ok";
    ok: SavedReport;
} | {
    __kind__: "err";
    err: AuthError;
};
export type UserId = Principal;
export type ReportId = bigint;
export type Result = {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: AuthError;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Array<SavedReport>;
} | {
    __kind__: "err";
    err: AuthError;
};
export interface Cell {
    value: Value;
    name: string;
}
export type SessionToken = string;
export interface SavedReport {
    id: ReportId;
    report: RiskReport;
    createdAt: bigint;
}
export interface RiskReport {
    findings: Array<Finding>;
    disclaimer: string;
    clinicalExplanation: string;
    riskLevel: RiskLevel;
}
export interface Finding {
    status: string;
    value: string;
    parameter: string;
    referenceRange: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface RiskAssessmentInput {
    prInterval: bigint;
    ultrasoundImage?: Uint8Array;
    stSegment: number;
    qrsDuration: bigint;
    temperature: number;
    spo2: bigint;
    complexes: string;
    qtInterval: bigint;
    rrInterval: bigint;
    heartRate: bigint;
}
export type Email = string;
export enum AuthError {
    invalidEmail = "invalidEmail",
    emailTaken = "emailTaken",
    notAuthenticated = "notAuthenticated",
    weakPassword = "weakPassword",
    invalidCredentials = "invalidCredentials"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    moderate = "moderate"
}
export interface backendInterface {
    assessRisk(input: RiskAssessmentInput): Promise<RiskReport>;
    execute(qJson: string): Promise<Result__1>;
    getApiDoc(): Promise<string>;
    getCurrentUser(token: SessionToken): Promise<User | null>;
    getMyReports(token: SessionToken): Promise<Result_3>;
    login(email: Email, password: string): Promise<Result_2>;
    logout(token: SessionToken): Promise<void>;
    saveReport(token: SessionToken, report: RiskReport): Promise<Result_1>;
    schema(): Promise<string>;
    signup(name: string, email: Email, password: string): Promise<Result>;
}
import type { AuthError as _AuthError, Cell as _Cell, Finding as _Finding, ReportId as _ReportId, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result__1 as _Result__1, RiskAssessmentInput as _RiskAssessmentInput, RiskLevel as _RiskLevel, RiskReport as _RiskReport, SavedReport as _SavedReport, SessionToken as _SessionToken, User as _User, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assessRisk(arg0: RiskAssessmentInput): Promise<RiskReport> {
        if (this.processError) {
            try {
                const result = await this.actor.assessRisk(to_candid_RiskAssessmentInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RiskReport_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assessRisk(to_candid_RiskAssessmentInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RiskReport_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCurrentUser(arg0: SessionToken): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReports(arg0: SessionToken): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReports(arg0);
                return from_candid_Result_3_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReports(arg0);
            return from_candid_Result_3_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: Email, arg1: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async saveReport(arg0: SessionToken, arg1: RiskReport): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReport(arg0, to_candid_RiskReport_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReport(arg0, to_candid_RiskReport_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async signup(arg0: string, arg1: Email, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.signup(arg0, arg1, arg2);
                return from_candid_Result_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signup(arg0, arg1, arg2);
            return from_candid_Result_n31(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthError_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthError): AuthError {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_RiskReport_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskReport): RiskReport {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_SavedReport_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SavedReport): SavedReport {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n13(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReportId;
    report: _RiskReport;
    createdAt: bigint;
}): {
    id: ReportId;
    report: RiskReport;
    createdAt: bigint;
} {
    return {
        id: value.id,
        report: from_candid_RiskReport_n3(_uploadFile, _downloadFile, value.report),
        createdAt: value.createdAt
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    findings: Array<_Finding>;
    disclaimer: string;
    clinicalExplanation: string;
    riskLevel: _RiskLevel;
}): {
    findings: Array<Finding>;
    disclaimer: string;
    clinicalExplanation: string;
    riskLevel: RiskLevel;
} {
    return {
        findings: value.findings,
        disclaimer: value.disclaimer,
        clinicalExplanation: value.clinicalExplanation,
        riskLevel: from_candid_RiskLevel_n5(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n9(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_SavedReport>;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: Array<SavedReport>;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n18(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n21(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidEmail: null;
} | {
    emailTaken: null;
} | {
    notAuthenticated: null;
} | {
    weakPassword: null;
} | {
    invalidCredentials: null;
}): AuthError {
    return "invalidEmail" in value ? AuthError.invalidEmail : "emailTaken" in value ? AuthError.emailTaken : "notAuthenticated" in value ? AuthError.notAuthenticated : "weakPassword" in value ? AuthError.weakPassword : "invalidCredentials" in value ? AuthError.invalidCredentials : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionToken;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n21(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SavedReport;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: SavedReport;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_SavedReport_n19(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n21(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n21(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    moderate: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "moderate" in value ? RiskLevel.moderate : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SavedReport>): Array<SavedReport> {
    return value.map((x)=>from_candid_SavedReport_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n10(_uploadFile, _downloadFile, x));
}
function to_candid_RiskAssessmentInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskAssessmentInput): _RiskAssessmentInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_RiskReport_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskReport): _RiskReport {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prInterval: bigint;
    ultrasoundImage?: Uint8Array;
    stSegment: number;
    qrsDuration: bigint;
    temperature: number;
    spo2: bigint;
    complexes: string;
    qtInterval: bigint;
    rrInterval: bigint;
    heartRate: bigint;
}): {
    prInterval: bigint;
    ultrasoundImage: [] | [Uint8Array];
    stSegment: number;
    qrsDuration: bigint;
    temperature: number;
    spo2: bigint;
    complexes: string;
    qtInterval: bigint;
    rrInterval: bigint;
    heartRate: bigint;
} {
    return {
        prInterval: value.prInterval,
        ultrasoundImage: value.ultrasoundImage ? candid_some(value.ultrasoundImage) : candid_none(),
        stSegment: value.stSegment,
        qrsDuration: value.qrsDuration,
        temperature: value.temperature,
        spo2: value.spo2,
        complexes: value.complexes,
        qtInterval: value.qtInterval,
        rrInterval: value.rrInterval,
        heartRate: value.heartRate
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    findings: Array<Finding>;
    disclaimer: string;
    clinicalExplanation: string;
    riskLevel: RiskLevel;
}): {
    findings: Array<_Finding>;
    disclaimer: string;
    clinicalExplanation: string;
    riskLevel: _RiskLevel;
} {
    return {
        findings: value.findings,
        disclaimer: value.disclaimer,
        clinicalExplanation: value.clinicalExplanation,
        riskLevel: to_candid_RiskLevel_n27(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    low: null;
} | {
    high: null;
} | {
    moderate: null;
} {
    return value == RiskLevel.low ? {
        low: null
    } : value == RiskLevel.high ? {
        high: null
    } : value == RiskLevel.moderate ? {
        moderate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
